server:
  port: 8890

logging:
  file: spring_boot_redis_log.log
  level: debug

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    pool:
      max-idle: 100
      min-idle: 10
      max-wait: 1000

